"""sync current schema

Revision ID: dd1ef35f5bac
Revises: 
Create Date: 2026-07-01 02:32:15.037225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1ef35f5bac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_invitations_candidate_id'), 'interview_invitations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_invitations_id'), 'interview_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_interview_invitations_job_id'), 'interview_invitations', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_invitations_job_id'), table_name='interview_invitations')
    op.drop_index(op.f('ix_interview_invitations_id'), table_name='interview_invitations')
    op.drop_index(op.f('ix_interview_invitations_candidate_id'), table_name='interview_invitations')
    op.drop_table('interview_invitations')
    # ### end Alembic commands ###
